use_frameworks!

target 'MyHeroesAPI_Example' do
  pod 'MyHeroesAPI', :path => '../'

  target 'MyHeroesAPI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
